---
title: "R and Python love story in Quarto"
format:
  html:
    code-fold: false
    self-contained: true
    theme: cosmo
execute:
  eval: true
  warning: false
engine: knitr
---

Combining R and Python code. Here via R using Knitr engine + reticulate library.

## Setup

```{r}
#library(reticulate)
#reticulate::conda_list()

#use_python("C:/Users/Lisa.Hornung/AppData/Local/miniconda3/envs/310_data_viz/")
#use_condaenv("310_data_viz")
```

## Load data in R and convert to pandas dataframe

```{r}
#R code
#library(readr)
#penguins <- read_csv("penguins_short.csv")

#convert to dataframe for python
#py_penguins <- r_to_py(penguins)
```


## Add column in python

```{python}
#Python code
#import pandas as pd

#print dataframe
#r.py_penguins

#add new column
#r.py_penguins["test_column"] = "test"
```

## Print new frame in R

```{r}
#R Code
#py_penguins
#r_penguins = py_to_r(py_penguins)
#r_penguins
```

## Test Observable Plot

```{ojs}
// Observable Plot code
aapl = [
  {Date: new Date("2013-05-13"), Open: 64.501427, High: 65.414284, Low: 64.500000, Close: 64.962860, Volume: 79237200},
  {Date: new Date("2013-05-14"), Open: 64.835716, High: 65.028572, Low: 63.164288, Close: 63.408573, Volume: 111779500},
  {Date: new Date("2013-05-15"), Open: 62.737144, High: 63.000000, Low: 60.337143, Close: 61.264286, Volume: 185403400},
  {Date: new Date("2013-05-16"), Open: 60.462856, High: 62.549999, Low: 59.842857, Close: 62.082859, Volume: 150801000},
  {Date: new Date("2013-05-17"), Open: 62.721428, High: 62.869999, Low: 61.572857, Close: 61.894287, Volume: 106976100}
]

Plot.plot({
  marks: [
    Plot.lineY(aapl, {x: "Date", y: "Close"})
  ]
})
```